# Generated by Django 4.2.8 on 2023-12-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('courses', models.TextField()),
                ('achievements', models.TextField()),
                ('acquired_GPA', models.IntegerField()),
                ('out_of_GPA', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('career_obj', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('achievements', models.TextField()),
                ('github', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.CharField(choices=[('b', 'Beginner'), ('i', 'Intermediate'), ('a', 'Advanced')], default='b', max_length=1)),
                ('type', models.CharField(choices=[('p', 'Programming Languages'), ('d', 'Databases'), ('f', 'Frameworks and Tools'), ('w', 'Web Technologies')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('achievements', models.TextField()),
            ],
        ),
    ]
