# Generated by Django 4.2.8 on 2023-12-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_projects_project_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='endDate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='startDate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='endDate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='startDate',
            field=models.CharField(max_length=100),
        ),
    ]
