# Generated by Django 4.2.8 on 2023-12-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_education_enddate_alter_education_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
