# Generated by Django 4.2.8 on 2023-12-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('date_acquired', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactMe',
        ),
        migrations.AlterField(
            model_name='education',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='acquired_GPA',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='education',
            name='courses',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='out_of_GPA',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
