# Generated by Django 5.0 on 2023-12-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_certificate_delete_contactme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
