# Generated by Django 5.0.1 on 2024-01-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_personalinfo_name_personalinfo_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
