# Generated by Django 5.0.1 on 2024-01-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_skill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('Beginner', 'BEGINNER'), ('Intermediate', 'INTERMEDIATE'), ('Advenced', 'ADVANCED')], default='b', max_length=100),
        ),
    ]
